### ISSUE TITLE
allelicBalance.py NameError

### ISSUE THREAD

**Issue by tbringloe** [joanam/scripts#5] opened 2021-03-19 00:54 UTC
Hi Joana, sorry to bother with what is probably a relatively simple query (I'm new to script writing with python and trying to work through the basics). I really want to run your allelicBalance.py script but it is coming up with a NameError: name 'alleles' is not defined. I've been scrutinizing the block structure of the script to see why this is not defined before being called on, I don't seem to be getting anywhere. Also, potentially there are issues with running a python 2 script on python 3 (I used 2to3 plugin just to be sure, same error)? I'm running latest python 3.9.2

Any help would be appreciated.

Trev

**Comment by joanam** [comment] 2021-03-19 15:02
Hi Trev,
Could it be that you have neither "/" nor "|" in your genotypes? You are giving it a vcf file of diploid individuals, right? One other problem could also be that you might have sites with more than three alleles. 
If it still does not work, I would need you to tell me the exact command to help me figure out what the problem is.
Best,
Joana

**Comment by tbringloe** [comment] 2021-03-19 21:08
Hi Joana, my dataset is mixed diploid and haploid, so I can see how that would present an issue (i.e. no / or | in genotypes for those individuals). Let me try removing the haploids and rerunning.

I will also filter for sites with more than 3 alleles.

Trev

**Comment by tbringloe** [comment] 2021-03-19 21:51
Hi Joana, I can confirm a few things. 1) the script runs fine one latest python version, however, tabs and spaces needed to be swapped so they are consistently used (one or the other). 2) there is a syntax error in the new error message: "Error: Please provide a vcf file of diploid individuals" should be put in parentheses. 3) the issue was the haploid samples and the script appears to work on a dataset of only diploid individuals. I not 100% sure if the output makes sense, as in the vcf file used I had not annotated with AD fields, so I'm not sure how the script would calculate allele depth (maybe you can provide insight here). I have a mixture of missing (-excl specified) and heterozygous alleles kept, the desired result, but the number of missing genotypes struck me as a too high. I can retry with a newer vcf file where I have AD annotations but I need to remove haploid individuals first.

Thanks for the help on this

Trev

**Comment by joanam** [comment] 2021-03-19 22:39
I have now fixed these issues, thanks for letting me know. The second issue is a Python version issue. I have now made it Python3-compatible. It should now also allow for haploid genotypes which it will just leave unchanged. However, not having AD annotations is a problem. The aim of the script is to remove heterozygous genotypes for which one allele is represented by way more reads than the other allele. If you do not have the read counts for each allele, that is a problem. However, if you have different read annotations, I could modify the script to allow for that.
Please let me know if it works with your file with AD in the second format column.

**Comment by tbringloe** [comment] 2021-03-19 23:34
Yes, I could not think how the script would work without AD, which begs the question of how it made its determinations without this annotation in the file I ran. In any case, getting the AD field is no problem, just need to recompile the vcf file. Can you clarify the need for AD in the second format column? Some of the annotation fields used by bcftools have become deprecated since this script was originally written. I try and annotate my vcf file with as many fields as possible: for instance, my most recent output provides GT:PL:DP:DP4:ADF:ADR:AD:GP:GQ 0/1:255,0,255:60:10,18,10,22:10,10:18,22:28,32:266,0,249:127. Would the script as is source the correct values for calculating AB, or should the annotations be reordered (not sure if bcftools has a function for that).

Happy to open a new issue if we're getting off topic here

Trev

**Comment by joanam** [comment] 2021-03-20 21:27
Hi Trev
I have now increased the flexibility of the script to allow the AD field to be at any position. In case there are some sites that do not have AD fields, e.g. monomorphic sites, the script will fail. The script can now also read and write gzipped files.
Best,
Joana

**Comment by tbringloe** [comment] 2021-03-21 23:48
Hi Joana, fantastic. Sorry to continue bothering but I think it is worth powering through and ensuring this script works for everyone (I've seen almost no options for filtering SNPs for allele balance, so this script is important in my view). Running the script comes up with:

Traceback (most recent call last):
  File "C:\Users\tbrin\Documents\scripts\jana\scripts-master\allelicBalance_new.py", line 50, in <module>
    if re.match('^#',Line) is None:
  File "C:\Users\tbrin\AppData\Local\Programs\Python\Python39\lib\re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object

My python knowledge is not good enough to troubleshoot. I should mention I had one haploid individual in the dataset; I noticed that the error message for haploid data was removed from the most recent iteration of the script. Can the script safely run with any haploid individuals, or do these need to be removed? I'm currently filtering my dataset and will remove this individual before rerunning the script.

Cheers

Trev

**Comment by joanam** [comment] 2021-03-22 17:30
I am glad that you think this script would be useful to others. Given that I do not have haploid individuals in my test dataset, there is probably some special exception I have not thought about. Could you maybe send me a test dataset for me to try to jm2276[AT]cam.ac.uk. I will then troubleshoot my script. Thanks for your patience!

**Closed as completed** 2021-04-26 22:03 UTC
